version: '3'

services:
  clamav:
    build: .
    ports:
      - 3310:3310
    environment: 
      - StreamMaxLength=100M
      - MaxFileSize=100M
#      - ScriptedUpdates=no
#      - PrivateMirror=http://192.168.123.118:8085
